### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by bcbrock** [kchristidis/kafka-orderer#2]
Hi Kostas,

I'm playing with the devel branch code now - thanks very much for writing up the installation instructions.  Here are a few minor problems with the instructions (referenced to the items in "give it a test run":

2) Must "git checkout devel" to access the code currently

3) The code assumes that numerous packages have been installed. I thought that maybe the intention was to install this in the Hyperledger fabric path, but I see you need packages that Hyperledger fabric does not include. 

5) I assume that "client" is the old name for what is now "bd_counter"

**Comment by kchristidis** [comment]
Hi Bishop, thanks for taking the time to report this (and all the other issues).

I renamed the sample client from `client` to `bd_counter` in preparation for merging with the `fabric` project, but I wasn't careful enough to make sure the README stayed current. Should be good now, let me know if you bump into any other inconsistencies.
